
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------


/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LPARENT_CUAD = 43;
  public static final int RPARENT = 42;
  public static final int LPARENT = 41;
  public static final int POWER = 27;
  public static final int CHAR = 3;
  public static final int ENTERO = 49;
  public static final int PRINT_INT = 20;
  public static final int PRINT_FLOAT = 21;
  public static final int INT = 2;
  public static final int INIBLOQUE = 45;
  public static final int RPARENT_CUAD = 44;
  public static final int FOR = 16;
  public static final int MINUS = 24;
  public static final int ENTERO_POSITIVO = 52;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int DIV = 26;
  public static final int PLUS = 23;
  public static final int MAIN = 10;
  public static final int IF = 11;
  public static final int ID = 53;
  public static final int DECIMAL = 50;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int READ_FLOAT = 19;
  public static final int RETURN = 9;
  public static final int TRUE = 7;
  public static final int error = 1;
  public static final int COMA = 47;
  public static final int CADENA = 51;
  public static final int DIF = 39;
  public static final int FINBLOQUE = 46;
  public static final int MAYOR_QUE = 34;
  public static final int FINEXP = 48;
  public static final int BREAK = 17;
  public static final int MODULE = 28;
  public static final int TIMES = 25;
  public static final int PLUS_UN = 29;
  public static final int MINUS_UN = 30;
  public static final int READ_INT = 18;
  public static final int ELSE = 13;
  public static final int WHILE = 15;
  public static final int MAYOR_IGUAL = 35;
  public static final int EQUIV = 40;
  public static final int FLOAT = 5;
  public static final int STRING = 4;
  public static final int DEQUIV = 38;
  public static final int MENOR_QUE = 36;
  public static final int MENOR_IGUAL = 37;
  public static final int FALSE = 8;
  public static final int ELIF = 12;
  public static final int PRINT_STRING = 22;
  public static final int DO = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "CHAR",
  "STRING",
  "FLOAT",
  "BOOLEAN",
  "TRUE",
  "FALSE",
  "RETURN",
  "MAIN",
  "IF",
  "ELIF",
  "ELSE",
  "DO",
  "WHILE",
  "FOR",
  "BREAK",
  "READ_INT",
  "READ_FLOAT",
  "PRINT_INT",
  "PRINT_FLOAT",
  "PRINT_STRING",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIV",
  "POWER",
  "MODULE",
  "PLUS_UN",
  "MINUS_UN",
  "AND",
  "OR",
  "NOT",
  "MAYOR_QUE",
  "MAYOR_IGUAL",
  "MENOR_QUE",
  "MENOR_IGUAL",
  "DEQUIV",
  "DIF",
  "EQUIV",
  "LPARENT",
  "RPARENT",
  "LPARENT_CUAD",
  "RPARENT_CUAD",
  "INIBLOQUE",
  "FINBLOQUE",
  "COMA",
  "FINEXP",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "ENTERO_POSITIVO",
  "ID"
  };
}

